const fs = require("fs");
const path = require("path");

const projectRoot = path.resolve(__dirname, "..", "..");
const sourcePath = path.join(projectRoot, "docs", "rocking_curves_neg_sres_app.html");
const summaryTxtPath = path.join(projectRoot, "docs", "rocking-curves-neg-sres", "summary.txt");
const summaryCsvPath = path.join(projectRoot, "docs", "rocking-curves-neg-sres", "summary.csv");
const outputPath = path.join(projectRoot, "docs", "rocking_curves_neg_sres_app_styled.html");

function readText(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function extractSourceParts(sourceHtml) {
  const scriptTags = [...sourceHtml.matchAll(/<script\b[^>]*>[\s\S]*?<\/script>/gi)].map((match) => match[0]);
  const plotlyConfigScript = scriptTags.find((tag) => tag.includes("window.PlotlyConfig"));
  const plotScript = scriptTags.find((tag) => tag.includes("Plotly.newPlot"));
  const plotlySrc = sourceHtml.match(/<script[^>]*src="([^"]*plotly[^"]*)"[^>]*><\/script>/i)?.[1];
  const plotDivId = sourceHtml.match(/<div id="([^"]+)" class="plotly-graph-div"[^>]*><\/div>/i)?.[1];

  if (!plotlyConfigScript || !plotScript || !plotlySrc || !plotDivId) {
    throw new Error("Could not extract the Plotly payload from the source HTML export.");
  }

  return { plotlyConfigScript, plotScript, plotlySrc, plotDivId };
}

function parseSummary(summaryTxt, summaryCsv) {
  const summaryLines = summaryTxt
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);

  const csvLines = summaryCsv
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);

  const reflectionCount = Math.max(csvLines.length - 1, 0);
  const firstDataRow = csvLines[1] || "";
  const firstMatch = firstDataRow.match(/^(\d+),[^,]*,[^,]*,[^,]*,"([^"]+)",([^,]+)/);

  const sourceLine = summaryLines.find((line) => line.startsWith("T1 SRES input:"));
  const sresColumnLine = summaryLines.find((line) => line.startsWith("SRES column:"));
  const alignLine = summaryLines.find((line) => line.startsWith("display_align_peaks="));
  const normalizeLine = summaryLines.find((line) => line.startsWith("display_normalize_max="));
  const offsetLine = summaryLines.find((line) => line.startsWith("display_offset_step="));
  const mappingLines = summaryLines
    .filter((line) => line.startsWith("- "))
    .map((line) => line.replace(/^- /, ""));

  const firstReflection = {
    rank: firstMatch ? Number(firstMatch[1]) : 1,
    hkl: firstMatch ? firstMatch[2] : "(0,0,-1)",
    sres: firstMatch ? Number(firstMatch[3]) : -29.865680975353907,
  };

  return {
    reflectionCount,
    firstReflection,
    sourceFile: sourceLine ? path.basename(sourceLine.split(":").slice(1).join(":").trim()) : "Unknown",
    sresColumn: sresColumnLine ? sresColumnLine.split(":").slice(1).join(":").trim() : "Unknown",
    alignPeaks: alignLine ? alignLine.split("=")[1].trim() : "True",
    normalizeMax: normalizeLine ? normalizeLine.split("=")[1].trim() : "True",
    offsetStep: offsetLine ? offsetLine.split("=")[1].trim() : "1.15",
    mappingLines,
  };
}

function formatInitialSummary(summary) {
  return [
    `T1 reflection ${summary.firstReflection.hkl} | rank=${summary.firstReflection.rank} | T1 SRES=${summary.firstReflection.sres.toFixed(6)}`,
    "Use the chart dropdown to inspect a different ranked reflection.",
  ];
}

function buildHtml(parts, summary) {
  const initialSummaryLines = formatInitialSummary(summary);
  const initialReflectionSummaryHtml = initialSummaryLines
    .slice(1)
    .map((line) => `<div class="summary-line">${escapeHtml(line)}</div>`)
    .join("\n");
  const mappingHtml = summary.mappingLines
    .map((line) => `<div class="mapping-item">${escapeHtml(line)}</div>`)
    .join("\n");
  const presetHtml = [
    `Source file: ${summary.sourceFile}`,
    `SRES column: ${summary.sresColumn}`,
    `Peak alignment: ${summary.alignPeaks === "True" ? "On" : "Off"}`,
    `Max normalization: ${summary.normalizeMax === "True" ? "On" : "Off"}`,
    `Vertical offset step: ${summary.offsetStep}`,
  ]
    .map((line) => `<div class="summary-item">${escapeHtml(line)}</div>`)
    .join("\n");

  const enhancementScript = [
    "<script>",
    `const graphId = ${JSON.stringify(parts.plotDivId)};`,
    `const reflectionCount = ${JSON.stringify(summary.reflectionCount)};`,
    `const initialSummaryLines = ${JSON.stringify(initialSummaryLines)};`,
    "",
    "function stripHtml(value) {",
    "  return String(value || '')",
    "    .replace(/<br\\s*\\/?>/gi, '\\n')",
    "    .replace(/<[^>]+>/g, '')",
    "    .replace(/&nbsp;/g, ' ')",
    "    .trim();",
    "}",
    "",
    "function summaryLinesFromAnnotation(annotationText) {",
    "  const text = stripHtml(annotationText);",
    "  if (!text) return initialSummaryLines.slice();",
    "  return text.split(/\\n+/).map((line) => line.trim()).filter(Boolean);",
    "}",
    "",
    "function renderSummaryLines(lines) {",
    "  const target = document.getElementById('reflectionSummary');",
    "  if (!target) return;",
    "  target.innerHTML = '';",
    "  lines.slice(1).forEach((line) => {",
    "    const item = document.createElement('div');",
    "    item.className = 'summary-line';",
    "    item.textContent = line;",
    "    target.appendChild(item);",
    "  });",
    "}",
    "",
    "function renderDatasetLegend(graphDiv) {",
    "  const target = document.getElementById('datasetLegend');",
    "  if (!target || !graphDiv || !Array.isArray(graphDiv.data)) return;",
    "  target.innerHTML = '';",
    "  graphDiv.data.forEach((trace) => {",
    "    const item = document.createElement('div');",
    "    item.className = 'legend-item';",
    "",
    "    const swatch = document.createElement('span');",
    "    swatch.className = 'swatch';",
    "    swatch.style.borderTopColor = trace?.line?.color || '#a14d2a';",
    "",
    "    const label = document.createElement('span');",
    "    label.textContent = trace?.name || 'Series';",
    "",
    "    item.appendChild(swatch);",
    "    item.appendChild(label);",
    "    target.appendChild(item);",
    "  });",
    "",
    "  const datasetCount = document.getElementById('datasetCount');",
    "  if (datasetCount) datasetCount.textContent = String(graphDiv.data.length || 0);",
    "}",
    "",
    "function buildAxisStyle(axis = {}) {",
    "  const titleText = typeof axis.title === 'string' ? axis.title : axis.title?.text || '';",
    "  return {",
    "    ...axis,",
    "    showline: true,",
    "    mirror: true,",
    "    linewidth: 1,",
    "    linecolor: '#8a785f',",
    "    gridcolor: '#d9cfbf',",
    "    zerolinecolor: '#bea889',",
    "    tickfont: {",
    "      family: 'Georgia, \"Times New Roman\", serif',",
    "      size: 12,",
    "      color: '#665948'",
    "    },",
    "    title: {",
    "      ...(typeof axis.title === 'object' ? axis.title : {}),",
    "      text: titleText,",
    "      standoff: 10,",
    "      font: {",
    "        family: 'Georgia, \"Times New Roman\", serif',",
    "        size: 15,",
    "        color: '#2c2419'",
    "      }",
    "    }",
    "  };",
    "}",
    "",
    "function applyPlotTheme(graphDiv) {",
    "  if (!window.Plotly || !graphDiv || !graphDiv.layout) return Promise.resolve();",
    "",
    "  const baseLayout = graphDiv.layout;",
    "  const isCompact = window.innerWidth < 980;",
    "  const titleText = typeof baseLayout.title === 'string' ? baseLayout.title : baseLayout.title?.text || '';",
    "  const annotations = (baseLayout.annotations || []).map((annotation) => ({",
    "    ...annotation,",
    "    bgcolor: 'rgba(255,253,248,0.94)',",
    "    bordercolor: '#cdbd9f',",
    "    borderpad: 6,",
    "    font: {",
    "      family: 'Georgia, \"Times New Roman\", serif',",
    "      size: 13,",
    "      color: '#2c2419'",
    "    }",
    "  }));",
    "",
    "  const updatemenus = (baseLayout.updatemenus || []).map((menu) => ({",
    "    ...menu,",
    "    bgcolor: '#fffdf8',",
    "    bordercolor: '#cdbd9f',",
    "    borderwidth: 1,",
    "    font: {",
    "      family: 'Georgia, \"Times New Roman\", serif',",
    "      size: 13,",
    "      color: '#2c2419'",
    "    },",
    "    x: isCompact ? 0 : 1,",
    "    xanchor: isCompact ? 'left' : 'right',",
    "    y: isCompact ? -0.18 : 1.08,",
    "    yanchor: isCompact ? 'top' : 'bottom'",
    "  }));",
    "",
    "  return window.Plotly.relayout(graphDiv, {",
    "    paper_bgcolor: 'rgba(0,0,0,0)',",
    "    plot_bgcolor: '#fffaf3',",
    "    font: {",
    "      family: 'Georgia, \"Times New Roman\", serif',",
    "      size: 14,",
    "      color: '#2c2419'",
    "    },",
    "    margin: {",
    "      l: 72,",
    "      r: isCompact ? 24 : 132,",
    "      t: 84,",
    "      b: isCompact ? 108 : 70",
    "    },",
    "    title: {",
    "      text: titleText,",
    "      x: 0.02,",
    "      xanchor: 'left',",
    "      font: {",
    "        family: 'Georgia, \"Times New Roman\", serif',",
    "        size: isCompact ? 22 : 28,",
    "        color: '#2c2419'",
    "      }",
    "    },",
    "    legend: {",
    "      ...(baseLayout.legend || {}),",
    "      bgcolor: 'rgba(255,253,248,0.92)',",
    "      bordercolor: '#cdbd9f',",
    "      borderwidth: 1,",
    "      font: {",
    "        family: 'Georgia, \"Times New Roman\", serif',",
    "        size: 12,",
    "        color: '#2c2419'",
    "      }",
    "    },",
    "    hoverlabel: {",
    "      bgcolor: '#fffaf3',",
    "      bordercolor: '#a14d2a',",
    "      font: {",
    "        family: 'Georgia, \"Times New Roman\", serif',",
    "        size: 13,",
    "        color: '#2c2419'",
    "      }",
    "    },",
    "    xaxis: buildAxisStyle(baseLayout.xaxis),",
    "    yaxis: buildAxisStyle(baseLayout.yaxis),",
    "    annotations,",
    "    updatemenus",
    "  }).catch(() => {});",
    "}",
    "",
    "function syncSidebar(graphDiv) {",
    "  if (!graphDiv || !graphDiv.layout) return;",
    "",
    "  const layout = graphDiv.layout;",
    "  const titleText = typeof layout.title === 'string' ? layout.title : layout.title?.text || '';",
    "  const annotationText = layout.annotations?.[0]?.text || '';",
    "  const lines = summaryLinesFromAnnotation(annotationText);",
    "",
    "  const plotHeading = document.getElementById('plotHeading');",
    "  if (plotHeading) plotHeading.textContent = titleText || 'Top negative T1-SRES reflection comparison';",
    "",
    "  const reflectionTitle = document.getElementById('reflectionTitle');",
    "  if (reflectionTitle) reflectionTitle.textContent = lines[0] || initialSummaryLines[0];",
    "",
    "  renderSummaryLines(lines);",
    "",
    "  const status = document.getElementById('plotStatus');",
    "  if (status) {",
    "    const buttonCount = layout.updatemenus?.[0]?.buttons?.length || reflectionCount;",
    "    status.textContent = `Use the plot dropdown to browse ${buttonCount} ranked reflections.`;",
    "  }",
    "}",
    "",
    "function attachGraphBehaviors(graphDiv) {",
    "  if (!graphDiv || typeof graphDiv.on !== 'function') return;",
    "  const refresh = () => setTimeout(() => syncSidebar(graphDiv), 0);",
    "  graphDiv.on('plotly_afterplot', refresh);",
    "  graphDiv.on('plotly_buttonclicked', refresh);",
    "  graphDiv.on('plotly_relayout', refresh);",
    "  graphDiv.on('plotly_restyle', refresh);",
    "}",
    "",
    "function initializeGraph(attempt = 0) {",
    "  const graphDiv = document.getElementById(graphId);",
    "  if (!graphDiv || !graphDiv.layout || !Array.isArray(graphDiv.data)) {",
    "    if (attempt < 60) {",
    "      window.setTimeout(() => initializeGraph(attempt + 1), 150);",
    "    }",
    "    return;",
    "  }",
    "",
    "  document.getElementById('reflectionCount').textContent = String(reflectionCount);",
    "  renderDatasetLegend(graphDiv);",
    "  attachGraphBehaviors(graphDiv);",
    "  applyPlotTheme(graphDiv).then(() => syncSidebar(graphDiv));",
    "",
    "  let resizeTimer = 0;",
    "  window.addEventListener('resize', () => {",
    "    window.clearTimeout(resizeTimer);",
    "    resizeTimer = window.setTimeout(() => {",
    "      applyPlotTheme(graphDiv).then(() => syncSidebar(graphDiv));",
    "    }, 160);",
    "  });",
    "}",
    "",
    "initializeGraph();",
    "</script>",
  ].join("\n");

  const htmlParts = [
    "<!DOCTYPE html>",
    "<html lang=\"en\">",
    "<head>",
    "  <meta charset=\"utf-8\" />",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
    "  <title>Negative T1-SRES Rocking Curves</title>",
    "  <meta",
    "    name=\"description\"",
    "    content=\"Styled Plotly report for the top negative T1-SRES reflections across four thickness datasets.\"",
    "  />",
    "  <style>",
    "    :root {",
    "      --bg: #f5f1e8;",
    "      --panel: #fffdf8;",
    "      --panel-strong: #f2e6d2;",
    "      --border: #cdbd9f;",
    "      --text: #2c2419;",
    "      --muted: #665948;",
    "      --accent: #a14d2a;",
    "      --accent-2: #206a5d;",
    "      --grid: #d9cfbf;",
    "      --shadow: 0 10px 30px rgba(54, 37, 15, 0.08);",
    "    }",
    "",
    "    * {",
    "      box-sizing: border-box;",
    "    }",
    "",
    "    html,",
    "    body {",
    "      margin: 0;",
    "      padding: 0;",
    "    }",
    "",
    "    body {",
    "      font-family: Georgia, \"Times New Roman\", serif;",
    "      color: var(--text);",
    "      background:",
    "        radial-gradient(circle at top left, rgba(161, 77, 42, 0.12), transparent 30%),",
    "        radial-gradient(circle at bottom right, rgba(32, 106, 93, 0.14), transparent 28%),",
    "        linear-gradient(180deg, #f7f3eb 0%, var(--bg) 100%);",
    "    }",
    "",
    "    .page {",
    "      max-width: 1340px;",
    "      margin: 0 auto;",
    "      padding: 24px;",
    "    }",
    "",
    "    .header {",
    "      margin-bottom: 20px;",
    "    }",
    "",
    "    .eyebrow {",
    "      letter-spacing: 0.18em;",
    "      text-transform: uppercase;",
    "      color: var(--accent);",
    "      font-size: 0.78rem;",
    "      margin-bottom: 6px;",
    "    }",
    "",
    "    h1 {",
    "      margin: 0;",
    "      font-size: clamp(2.2rem, 4.2vw, 3.7rem);",
    "      line-height: 0.95;",
    "      font-weight: 700;",
    "      max-width: 900px;",
    "    }",
    "",
    "    .subtitle {",
    "      max-width: 860px;",
    "      margin-top: 12px;",
    "      color: var(--muted);",
    "      font-size: 1rem;",
    "      line-height: 1.55;",
    "    }",
    "",
    "    .hero-stats {",
    "      display: grid;",
    "      grid-template-columns: repeat(3, minmax(0, 1fr));",
    "      gap: 14px;",
    "      margin-top: 18px;",
    "    }",
    "",
    "    .stat-card {",
    "      background: rgba(255, 253, 248, 0.84);",
    "      border: 1px solid rgba(205, 189, 159, 0.9);",
    "      border-radius: 16px;",
    "      padding: 14px 16px;",
    "      box-shadow: var(--shadow);",
    "      backdrop-filter: blur(8px);",
    "    }",
    "",
    "    .stat-label {",
    "      display: block;",
    "      color: var(--muted);",
    "      font-size: 0.82rem;",
    "      letter-spacing: 0.08em;",
    "      text-transform: uppercase;",
    "      margin-bottom: 6px;",
    "    }",
    "",
    "    .stat-value {",
    "      display: block;",
    "      font-size: 1.3rem;",
    "      font-weight: 700;",
    "      color: var(--text);",
    "    }",
    "",
    "    .stat-copy {",
    "      margin-top: 4px;",
    "      color: var(--muted);",
    "      font-size: 0.92rem;",
    "      line-height: 1.45;",
    "    }",
    "",
    "    .layout {",
    "      display: grid;",
    "      grid-template-columns: 340px minmax(0, 1fr);",
    "      gap: 20px;",
    "      align-items: start;",
    "    }",
    "",
    "    .panel {",
    "      background: var(--panel);",
    "      border: 1px solid var(--border);",
    "      border-radius: 18px;",
    "      box-shadow: var(--shadow);",
    "    }",
    "",
    "    .controls {",
    "      padding: 18px;",
    "      position: sticky;",
    "      top: 18px;",
    "    }",
    "",
    "    .plot-panel {",
    "      padding: 16px;",
    "      overflow: hidden;",
    "    }",
    "",
    "    .note {",
    "      background: var(--panel-strong);",
    "      border: 1px solid var(--border);",
    "      border-radius: 14px;",
    "      padding: 12px 14px;",
    "      margin-bottom: 16px;",
    "      line-height: 1.5;",
    "      color: var(--text);",
    "    }",
    "",
    "    .control-group {",
    "      margin-bottom: 18px;",
    "    }",
    "",
    "    .control-inline-title {",
    "      display: block;",
    "      font-size: 0.92rem;",
    "      margin-bottom: 8px;",
    "      color: var(--text);",
    "      font-weight: 700;",
    "    }",
    "",
    "    .mini-stats {",
    "      display: grid;",
    "      grid-template-columns: repeat(2, minmax(0, 1fr));",
    "      gap: 10px;",
    "    }",
    "",
    "    .mini-stat {",
    "      background: #fffaf3;",
    "      border: 1px solid var(--border);",
    "      border-radius: 12px;",
    "      padding: 10px 12px;",
    "    }",
    "",
    "    .mini-label {",
    "      display: block;",
    "      font-size: 0.8rem;",
    "      color: var(--muted);",
    "      margin-bottom: 4px;",
    "      text-transform: uppercase;",
    "      letter-spacing: 0.06em;",
    "    }",
    "",
    "    .mini-value {",
    "      display: block;",
    "      font-size: 1.18rem;",
    "      font-weight: 700;",
    "    }",
    "",
    "    .summary-stack,",
    "    .mapping-stack,",
    "    .reflection-stack {",
    "      display: grid;",
    "      gap: 8px;",
    "    }",
    "",
    "    .summary-item,",
    "    .mapping-item,",
    "    .summary-line {",
    "      background: #fffaf3;",
    "      border: 1px solid rgba(205, 189, 159, 0.78);",
    "      border-radius: 12px;",
    "      padding: 9px 11px;",
    "      color: var(--muted);",
    "      font-size: 0.92rem;",
    "      line-height: 1.42;",
    "    }",
    "",
    "    .selected-title {",
    "      color: var(--text);",
    "      font-size: 1.08rem;",
    "      line-height: 1.4;",
    "      font-weight: 700;",
    "      padding: 12px 14px;",
    "      border-radius: 14px;",
    "      background: linear-gradient(180deg, #fff8ee 0%, #f6ebd9 100%);",
    "      border: 1px solid var(--border);",
    "    }",
    "",
    "    .plot-topbar {",
    "      display: flex;",
    "      justify-content: space-between;",
    "      gap: 12px;",
    "      align-items: flex-start;",
    "      margin-bottom: 10px;",
    "      flex-wrap: wrap;",
    "    }",
    "",
    "    .plot-title {",
    "      font-size: 1.32rem;",
    "      font-weight: 700;",
    "      margin: 0;",
    "      max-width: 760px;",
    "    }",
    "",
    "    .status {",
    "      min-height: 1.3em;",
    "      color: var(--accent);",
    "      font-size: 0.96rem;",
    "      margin-top: 6px;",
    "    }",
    "",
    "    .badge-cluster {",
    "      display: flex;",
    "      gap: 10px;",
    "      flex-wrap: wrap;",
    "    }",
    "",
    "    .badge {",
    "      display: inline-flex;",
    "      align-items: center;",
    "      min-height: 34px;",
    "      padding: 0 12px;",
    "      border-radius: 999px;",
    "      background: var(--panel-strong);",
    "      border: 1px solid var(--border);",
    "      color: var(--text);",
    "      font-size: 0.88rem;",
    "      font-weight: 600;",
    "    }",
    "",
    "    .badge-alt {",
    "      background: rgba(32, 106, 93, 0.12);",
    "      color: #174d44;",
    "      border-color: rgba(32, 106, 93, 0.25);",
    "    }",
    "",
    "    .plot-shell {",
    "      width: 100%;",
    "      min-height: 680px;",
    "      border-radius: 16px;",
    "      background:",
    "        linear-gradient(180deg, rgba(255,255,255,0.76), rgba(245, 241, 232, 0.92)),",
    "        repeating-linear-gradient(",
    "          135deg,",
    "          rgba(161, 77, 42, 0.04),",
    "          rgba(161, 77, 42, 0.04) 12px,",
    "          rgba(32, 106, 93, 0.03) 12px,",
    "          rgba(32, 106, 93, 0.03) 24px",
    "        );",
    "      border: 1px solid var(--border);",
    "      overflow: hidden;",
    "      padding: 8px;",
    "    }",
    "",
    "    .styled-plot-root,",
    "    .styled-plot-root .plot-container,",
    "    .styled-plot-root .svg-container {",
    "      width: 100% !important;",
    "    }",
    "",
    "    .styled-plot-root {",
    "      height: clamp(560px, 74vh, 880px) !important;",
    "    }",
    "",
    "    .plot-shell .js-plotly-plot .plotly .modebar {",
    "      background: rgba(255, 253, 248, 0.92);",
    "      border: 1px solid rgba(205, 189, 159, 0.92);",
    "      border-radius: 12px;",
    "      box-shadow: 0 6px 16px rgba(54, 37, 15, 0.08);",
    "      padding: 4px;",
    "    }",
    "",
    "    .plot-shell .js-plotly-plot .plotly .modebar-btn {",
    "      color: var(--muted) !important;",
    "    }",
    "",
    "    .legend {",
    "      display: flex;",
    "      flex-wrap: wrap;",
    "      gap: 10px 16px;",
    "    }",
    "",
    "    .legend-item {",
    "      display: inline-flex;",
    "      align-items: center;",
    "      gap: 8px;",
    "      color: var(--muted);",
    "      font-size: 0.93rem;",
    "    }",
    "",
    "    .swatch {",
    "      width: 24px;",
    "      height: 0;",
    "      border-top-width: 3px;",
    "      border-top-style: solid;",
    "      flex: 0 0 auto;",
    "    }",
    "",
    "    .footer-note {",
    "      margin-top: 12px;",
    "      color: var(--muted);",
    "      font-size: 0.9rem;",
    "      line-height: 1.45;",
    "    }",
    "",
    "    @media (max-width: 980px) {",
    "      .layout {",
    "        grid-template-columns: 1fr;",
    "      }",
    "",
    "      .controls {",
    "        position: static;",
    "      }",
    "",
    "      .hero-stats {",
    "        grid-template-columns: 1fr;",
    "      }",
    "",
    "      .plot-shell {",
    "        min-height: 520px;",
    "      }",
    "",
    "      .styled-plot-root {",
    "        height: clamp(500px, 68vh, 760px) !important;",
    "      }",
    "    }",
    "",
    "    @media (max-width: 640px) {",
    "      .page {",
    "        padding: 16px;",
    "      }",
    "",
    "      .mini-stats {",
    "        grid-template-columns: 1fr 1fr;",
    "      }",
    "",
    "      .plot-panel {",
    "        padding: 12px;",
    "      }",
    "    }",
    "  </style>",
    "</head>",
    "<body>",
    "  <div class=\"page\">",
    "    <header class=\"header\">",
    "      <div class=\"eyebrow\">Interactive Plotly Report</div>",
    "      <h1>Negative T1-SRES Rocking Curves</h1>",
    "      <div class=\"subtitle\">",
    "        A styled companion to the original Plotly export, keeping the same reflection ranking,",
    "        dropdown navigation, alignment, normalization, and trace data while borrowing the warmer",
    "        editorial layout language from the absorption rocking-curve app.",
    "      </div>",
    "",
    "      <div class=\"hero-stats\">",
    "        <div class=\"stat-card\">",
    "          <span class=\"stat-label\">Ranked Reflections</span>",
    `          <span class="stat-value">${escapeHtml(String(summary.reflectionCount))}</span>`,
    "          <div class=\"stat-copy\">Curated from the most negative T1-SRES values in the report summary.</div>",
    "        </div>",
    "        <div class=\"stat-card\">",
    "          <span class=\"stat-label\">Datasets Compared</span>",
    "          <span class=\"stat-value\">4 thicknesses</span>",
    "          <div class=\"stat-copy\">t1 100 nm, t2 200 nm, t3 350 nm, and t4 600 nm remain overlaid in every view.</div>",
    "        </div>",
    "        <div class=\"stat-card\">",
    "          <span class=\"stat-label\">Current Lead Reflection</span>",
    `          <span class="stat-value">#${escapeHtml(String(summary.firstReflection.rank))} ${escapeHtml(summary.firstReflection.hkl)}</span>`,
    `          <div class="stat-copy">Initial T1 SRES = ${escapeHtml(summary.firstReflection.sres.toFixed(3))}; the sidebar updates when you switch reflections.</div>`,
    "        </div>",
    "      </div>",
    "    </header>",
    "",
    "    <div class=\"layout\">",
    "      <aside class=\"panel controls\">",
    "        <div class=\"note\">",
    "          This copy preserves the original Plotly interaction model. The only changes are the page shell,",
    "          supporting summary cards, and a warmer theme applied on top of the existing figure.",
    "        </div>",
    "",
    "        <div class=\"control-group\">",
    "          <div class=\"control-inline-title\">Report Overview</div>",
    "          <div class=\"mini-stats\">",
    "            <div class=\"mini-stat\">",
    "              <span class=\"mini-label\">Reflections</span>",
    `              <span id="reflectionCount" class="mini-value">${escapeHtml(String(summary.reflectionCount))}</span>`,
    "            </div>",
    "            <div class=\"mini-stat\">",
    "              <span class=\"mini-label\">Datasets</span>",
    "              <span id=\"datasetCount\" class=\"mini-value\">4</span>",
    "            </div>",
    "          </div>",
    "        </div>",
    "",
    "        <div class=\"control-group\">",
    "          <div class=\"control-inline-title\">Selected Reflection</div>",
    `          <div id="reflectionTitle" class="selected-title">${escapeHtml(initialSummaryLines[0])}</div>`,
    `          <div id="reflectionSummary" class="reflection-stack">${initialReflectionSummaryHtml}</div>`,
    "        </div>",
    "",
    "        <div class=\"control-group\">",
    "          <div class=\"control-inline-title\">Dataset Traces</div>",
    "          <div id=\"datasetLegend\" class=\"legend\"></div>",
    "        </div>",
    "",
    "        <div class=\"control-group\">",
    "          <div class=\"control-inline-title\">Display Preset</div>",
    "          <div class=\"summary-stack\">",
    presetHtml,
    "          </div>",
    "        </div>",
    "",
    "        <div class=\"control-group\">",
    "          <div class=\"control-inline-title\">Dataset Mapping</div>",
    "          <div class=\"mapping-stack\">",
    mappingHtml,
    "          </div>",
    "        </div>",
    "      </aside>",
    "",
    "      <section class=\"panel plot-panel\">",
    "        <div class=\"plot-topbar\">",
    "          <div>",
    `            <h2 id="plotHeading" class="plot-title">Top negative T1-SRES reflection ${escapeHtml(summary.firstReflection.hkl)} across 4 thicknesses</h2>`,
    `            <div id="plotStatus" class="status">Use the plot dropdown to browse ${escapeHtml(String(summary.reflectionCount))} ranked reflections.</div>`,
    "          </div>",
    "          <div class=\"badge-cluster\">",
    "            <span class=\"badge\">Original traces preserved</span>",
    "            <span class=\"badge badge-alt\">Styled page shell</span>",
    "          </div>",
    "        </div>",
    "",
    "        <div class=\"plot-shell\">",
    `          ${parts.plotlyConfigScript}`,
    `          <script charset="utf-8" src="${parts.plotlySrc}"></script>`,
    `          <div id="${parts.plotDivId}" class="plotly-graph-div styled-plot-root" style="height:100%; width:100%;"></div>`,
    `          ${parts.plotScript}`,
    "        </div>",
    "",
    "        <div class=\"footer-note\">",
    "          The card layout, palette, and typography are intentionally aligned with",
    "          <code>webapp/rocking_curve_abs_app.html</code>, while the plot content and controls still come",
    "          directly from the raw Plotly export.",
    "        </div>",
    "      </section>",
    "    </div>",
    "  </div>",
    enhancementScript,
    "</body>",
    "</html>",
    "",
  ];

  return htmlParts.join("\n");
}

function main() {
  const sourceHtml = readText(sourcePath);
  const summaryTxt = readText(summaryTxtPath);
  const summaryCsv = readText(summaryCsvPath);

  const parts = extractSourceParts(sourceHtml);
  const summary = parseSummary(summaryTxt, summaryCsv);
  const html = buildHtml(parts, summary);

  fs.writeFileSync(outputPath, html, "utf8");
  console.log(`Wrote ${outputPath}`);
}

main();
